export {
  AMPHITHEATER_PIT_RADIUS,
  BAMBOO_CLEARING_RADIUS,
  DEFAULT_STAGE,
  DEFAULT_SELECT_STAGE,
  MOUNTAINTOP_RADIUS,
  STAGE_DEFS,
  WOODEN_PIER_RADIUS,
  normalizeStageId,
} from '../stages/index.js';
