import { ARENA_RADIUS } from '../core/Constants.js';

export const DEFAULT_STAGE = 'test';
export const AMPHITHEATER_PIT_RADIUS = 6.77;
export const BAMBOO_CLEARING_RADIUS = 4.6;
export const MOUNTAINTOP_RADIUS = 3.35;
export const WOODEN_PIER_RADIUS = 3.55;

export const STAGE_DEFS = Object.freeze({
  test: Object.freeze({
    id: 'test',
    displayName: 'Test',
    description: 'Clean circular gameplay test arena',
    environment: Object.freeze({
      background: 0x111118,
      fogColor: 0x111118,
      fogDensity: 0.04,
    }),
    bounds: Object.freeze({ type: 'circle', radius: ARENA_RADIUS, boundary: 'cliff' }),
  }),
  amphitheater: Object.freeze({
    id: 'amphitheater',
    displayName: 'Amphitheater',
    description: 'Sun-baked amphitheater with dust and hard noon light',
    modelPath: '/stages/ancient_amphitheater_manual_patch_v1.glb',
    modelScale: 32,
    modelRotationY: 1.5707963267948966,
    modelYOffset: 4.65,
    showBoundaryMarkers: false,
    camera: Object.freeze({
      maxRadius: 5.8,
    }),
    backdrop: Object.freeze({
      type: 'none',
      blockerRadius: 15.9,
      blockerHeight: 2.8,
      blockerY: 0.75,
      blockerColor: 0x5d4b38,
    }),
    environment: Object.freeze({
      background: 0xb8d7ea,
      fogColor: 0xcaa875,
      fogDensity: 0.007,
    }),
    lighting: Object.freeze({
      sun: Object.freeze({
        color: 0xffdf9b,
        intensity: 2.1,
        position: Object.freeze([-7, 14, 6]),
      }),
      hemisphere: Object.freeze({
        skyColor: 0xd8ecff,
        groundColor: 0x6d4a2d,
        intensity: 0.52,
      }),
      fill: Object.freeze({
        color: 0xc27842,
        intensity: 0.12,
      }),
    }),
    atmosphere: Object.freeze({
      type: 'amphitheater_sun_dust',
      dustColor: 0xe0b26e,
      dustOpacity: 0.2,
      shaftColor: 0xffc46f,
      shaftOpacity: 0.34,
      hazeOpacity: 0.16,
      heatColor: 0xfff4de,
      heatOpacity: 0.105,
      heatStrength: 1.25,
      cloudColor: 0xfff0d2,
      cloudOpacity: 0.68,
      cloudShadowColor: 0xc2a37a,
      cloudShadowOpacity: 0.28,
      exteriorCityColor: 0x9f8360,
      exteriorCityOpacity: 0.86,
      exteriorCityShadowColor: 0x5d4632,
      exteriorCityShadowOpacity: 0.58,
      exteriorCityRoofColor: 0x765238,
      exteriorCityHazeColor: 0xf2d2a0,
      exteriorCityHazeOpacity: 0.12,
      exteriorCityRadius: 18.4,
      exteriorCityBaseY: 4.45,
      exteriorCityLowerRadius: 18.65,
      exteriorCityLowerBaseY: 1.05,
    }),
    materialMood: Object.freeze({
      tint: 0xb99567,
      tintStrength: 0.18,
      roughness: 0.96,
      metalnessMax: 0.03,
    }),
    bounds: Object.freeze({ type: 'circle', radius: AMPHITHEATER_PIT_RADIUS, boundary: 'wall' }),
  }),
  bamboo_clearing: Object.freeze({
    id: 'bamboo_clearing',
    displayName: 'Bamboo Clearing',
    description: 'Small clearing enclosed by dense bamboo',
    modelPath: '/stages/bamboo_courtyard_raw.glb',
    modelScale: 19.5,
    modelYOffset: 2.78,
    showBoundaryMarkers: false,
    features: Object.freeze({
      dawnSideLight: true,
      sunShafts: true,
      groundGlow: true,
      groundMist: true,
      denseBambooWall: true,
      dirtLeafFloor: false,
      stoneLantern: true,
      ambientMotion: true,
      fireflies: true,
    }),
    camera: Object.freeze({
      maxRadius: 4.15,
    }),
    pitFloor: Object.freeze({
      feature: 'dirtLeafFloor',
      texture: 'bamboo_leaf_litter',
      radius: BAMBOO_CLEARING_RADIUS,
      y: 0.028,
      color: 0x6b5030,
    }),
    decorModels: Object.freeze([
      Object.freeze({
        path: '/stages/bamboo_forest_cluster.glb',
        mode: 'ring',
        count: 24,
        radius: 7.35,
        radialJitter: 0.45,
        angleJitter: 0.07,
        scaleMin: 3.7,
        scaleMax: 5.0,
        faceCenter: true,
        rotationJitter: 0.22,
        groundSink: 0.65,
        sway: true,
        swayFeature: 'ambientMotion',
        swaySpeed: 0.11,
        swayX: 0.003,
        swayZ: 0.006,
      }),
      Object.freeze({
        path: '/stages/bamboo_forest_cluster.glb',
        mode: 'ring',
        count: 16,
        radius: 10.1,
        radialJitter: 0.8,
        angleJitter: 0.12,
        scaleMin: 5.8,
        scaleMax: 7.6,
        faceCenter: true,
        rotationJitter: 0.35,
        groundSink: 0.85,
        sway: true,
        swayFeature: 'ambientMotion',
        swaySpeed: 0.09,
        swayX: 0.002,
        swayZ: 0.004,
      }),
      Object.freeze({
        feature: 'denseBambooWall',
        path: '/stages/bamboo_forest_cluster.glb',
        mode: 'ring',
        count: 24,
        radius: 12.4,
        radialJitter: 1.1,
        angleJitter: 0.14,
        scaleMin: 7.8,
        scaleMax: 10.6,
        faceCenter: true,
        rotationJitter: 0.42,
        groundSink: 1.05,
        materialTint: 0x182d1d,
        materialOpacity: 0.9,
        materialStyle: 'matte',
        sway: true,
        swayFeature: 'ambientMotion',
        swaySpeed: 0.075,
        swayX: 0.0015,
        swayZ: 0.003,
      }),
    ]),
    environment: Object.freeze({
      background: 0x6f8a6d,
      fogColor: 0x2f5137,
      fogDensity: 0.03,
    }),
    lighting: Object.freeze({
      sun: Object.freeze({
        feature: 'dawnSideLight',
        color: 0xffb45f,
        intensity: 2.05,
        position: Object.freeze([-8, 8, -4.5]),
      }),
      hemisphere: Object.freeze({
        skyColor: 0x9fbf86,
        groundColor: 0x172b18,
        intensity: 0.72,
      }),
      fill: Object.freeze({
        color: 0x4e8054,
        intensity: 0.24,
      }),
    }),
    atmosphere: Object.freeze({
      type: 'bamboo_dawn',
      shaftColor: 0xffd27a,
      shaftOpacity: 0.34,
      groundGlowColor: 0xffc36b,
      groundGlowOpacity: 0.035,
      leafColor: 0x85b765,
      mistColor: 0xb7d6aa,
      fireflyColor: 0xdfff93,
      pollenColor: 0xd8d8a6,
    }),
    bounds: Object.freeze({ type: 'circle', radius: BAMBOO_CLEARING_RADIUS, boundary: 'wall' }),
  }),
  wooden_pier: Object.freeze({
    id: 'wooden_pier',
    displayName: 'Wooden Pier',
    description: 'Damaged dock platform over open water at sunset',
    modelPath: '/stages/wooden_pier_sunset_v1.glb',
    modelScale: 8.9,
    modelRotationY: 1.5707963267948966,
    modelYOffset: 0.24,
    showBoundaryMarkers: false,
    camera: Object.freeze({
      maxRadius: 4.25,
    }),
    decorModels: Object.freeze([
      Object.freeze({
        path: '/stages/wooden_ships_background.glb',
        mode: 'placements',
        materialTint: 0x6e7d82,
        materialOpacity: 0.36,
        materialStyle: 'matte',
        castShadow: false,
        receiveShadow: false,
        placements: Object.freeze([
          Object.freeze({
            position: Object.freeze([-16, 0.49, -21]),
            rotationY: 0.92,
            scale: Object.freeze([2.6, 2.35, 2.9]),
            drift: Object.freeze({ x: 0.42, y: 0.01, z: 0.16, yaw: 0.02, speed: 0.075, bobSpeed: 0.22, phase: 0.4 }),
          }),
          Object.freeze({
            position: Object.freeze([22, 0.25, -29]),
            rotationY: -0.72,
            scale: Object.freeze([1.75, 1.6, 1.95]),
          }),
        ]),
      }),
      Object.freeze({
        path: '/stages/wooden_sailboat_background.glb',
        mode: 'placements',
        materialTint: 0x8f8170,
        materialOpacity: 0.42,
        materialStyle: 'matte',
        castShadow: false,
        receiveShadow: false,
        placements: Object.freeze([
          Object.freeze({
            position: Object.freeze([-9, 0.23, -32]),
            rotationY: 0.34,
            scale: Object.freeze([1.25, 1.18, 1.35]),
          }),
          Object.freeze({
            position: Object.freeze([24, 0.35, -21]),
            rotationY: -0.18,
            scale: Object.freeze([1.55, 1.48, 1.68]),
            drift: Object.freeze({ x: -0.32, y: 0.012, z: 0.1, yaw: 0.024, speed: 0.064, bobSpeed: 0.2, phase: 2.1 }),
          }),
          Object.freeze({
            position: Object.freeze([18, 0.16, -12]),
            rotationY: -1.18,
            scale: Object.freeze([1.1, 1.02, 1.18]),
          }),
        ]),
      }),
      Object.freeze({
        path: '/stages/pier_island_background.glb',
        mode: 'placements',
        materialTint: 0x7c896b,
        materialOpacity: 0.94,
        castShadow: false,
        receiveShadow: false,
        placements: Object.freeze([
          Object.freeze({
            position: Object.freeze([0, -0.12, 18]),
            rotationY: -0.72,
            scale: Object.freeze([40, 2.0, 15]),
            waterShadow: Object.freeze({
              scale: Object.freeze([46, 12]),
              offset: Object.freeze([0, 0, -1.2]),
              rotationZ: 0.04,
              opacity: 0.2,
            }),
          }),
        ]),
      }),
      Object.freeze({
        path: '/stages/pier_island_background.glb',
        mode: 'placements',
        materialTint: 0x5f7f73,
        materialOpacity: 0.52,
        castShadow: false,
        receiveShadow: false,
        placements: Object.freeze([
          Object.freeze({
            position: Object.freeze([1, 0.06, -38]),
            rotationY: -0.34,
            scale: Object.freeze([9.4, 2.4, 5.0]),
            waterShadow: Object.freeze({
              scale: Object.freeze([13.5, 5.2]),
              offset: Object.freeze([0.3, 0, 1.6]),
              rotationZ: -0.18,
              opacity: 0.36,
            }),
          }),
          Object.freeze({
            position: Object.freeze([9, 0.04, -41]),
            rotationY: 0.18,
            scale: Object.freeze([6.6, 2.0, 3.8]),
            waterShadow: Object.freeze({
              scale: Object.freeze([9.2, 3.8]),
              offset: Object.freeze([-0.2, 0, 1.3]),
              rotationZ: 0.12,
              opacity: 0.32,
            }),
          }),
        ]),
      }),
    ]),
    environment: Object.freeze({
      background: 0xf0a061,
      fogColor: 0xd47754,
      fogDensity: 0.012,
    }),
    lighting: Object.freeze({
      sun: Object.freeze({
        color: 0xff9b55,
        intensity: 1.65,
        position: Object.freeze([-7.5, 5.4, -8.2]),
      }),
      hemisphere: Object.freeze({
        skyColor: 0xffbd7a,
        groundColor: 0x17324a,
        intensity: 0.62,
      }),
      fill: Object.freeze({
        color: 0x365f8f,
        intensity: 0.18,
      }),
    }),
    atmosphere: Object.freeze({
      type: 'pier_sunset',
      waterColor: 0x45bfda,
      waterHighlightColor: 0xe8ffff,
      waterHorizonColor: 0xffd3a2,
      waterCausticColor: 0xcff8ff,
      waterCausticStrength: 0.055,
      waterOpacity: 1.0,
      waterY: -0.3,
      hazeColor: 0xffc28a,
      horizonHazeOpacity: 0.56,
      horizonY: 0.25,
      skyHazeOpacity: 0.42,
      reflectionColor: 0xffdda0,
      reflectionOpacity: 0.045,
      cloudColor: 0xffc5a0,
      cloudOpacity: 0.18,
      mistOpacity: 0.2,
      seaBreezeColor: 0xdffcff,
      seaBreezeOpacity: 0.13,
      sunColor: 0xff8e45,
    }),
    materialMood: Object.freeze({
      tint: 0xc98d5b,
      tintStrength: 0.12,
      roughness: 0.9,
      metalnessMax: 0.05,
    }),
    bounds: Object.freeze({
      type: 'rect',
      minX: -4.33,
      maxX: 4.04,
      minZ: -3.52,
      maxZ: 2.68,
      boundary: 'cliff',
    }),
  }),
  mountaintop: Object.freeze({
    id: 'mountaintop',
    displayName: 'Mountaintop',
    description: 'Tiny storm-lashed summit above distant mountains',
    modelPath: '/stages/mountaintop_rock_pillar_raw.glb',
    modelScale: 11,
    modelYOffset: -3.62,
    showBoundaryMarkers: false,
    camera: Object.freeze({
      maxRadius: 5.4,
    }),
    decorModels: Object.freeze([
      Object.freeze({
        path: '/stages/pyramidal_mountain_raw.glb',
        mode: 'placements',
        materialTint: 0x0b1220,
        materialOpacity: 0.94,
        materialStyle: 'matte',
        placements: Object.freeze([
          Object.freeze({
            position: Object.freeze([-30, -3.6, -18]),
            rotationY: -0.8,
            scale: Object.freeze([28, 20, 24]),
          }),
          Object.freeze({
            position: Object.freeze([-9, -3.8, -28]),
            rotationY: -0.12,
            scale: Object.freeze([34, 26, 31]),
          }),
          Object.freeze({
            position: Object.freeze([17, -3.7, -25]),
            rotationY: 0.34,
            scale: Object.freeze([32, 24, 29]),
          }),
          Object.freeze({
            position: Object.freeze([39, -3.5, -17]),
            rotationY: 0.9,
            scale: Object.freeze([27, 19, 23]),
          }),
        ]),
      }),
    ]),
    environment: Object.freeze({
      background: 0x02050a,
      fogColor: 0x0b1421,
      fogDensity: 0.032,
    }),
    lighting: Object.freeze({
      sun: Object.freeze({
        color: 0x83a7d7,
        intensity: 0.62,
        position: Object.freeze([-6, 10, -4]),
      }),
      hemisphere: Object.freeze({
        skyColor: 0x17263a,
        groundColor: 0x08090d,
        intensity: 0.24,
      }),
      fill: Object.freeze({
        color: 0x1b2e48,
        intensity: 0.09,
      }),
    }),
    atmosphere: Object.freeze({
      type: 'mountaintop_clouds',
      cloudColor: 0x26303d,
      cloudOpacity: 0.76,
      cloudY: -1.15,
    }),
    bounds: Object.freeze({ type: 'circle', radius: MOUNTAINTOP_RADIUS, boundary: 'cliff' }),
  }),
});

export function normalizeStageId(stageId) {
  return STAGE_DEFS[stageId] ? stageId : DEFAULT_STAGE;
}
